services:
  db:
    image: postgres:16
    container_name: tfg_postgres
    restart: always
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: project_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: tfg_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://project_user:project_pass@db:5432/project_db
    volumes:
      - .:/code

volumes:
  postgres_data: